version: '3.7'

services:
  web:
    build: ./
    container_name: tg_api_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: tg_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: tg_api_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
    depends_on:
      - web

volumes:
  postgres_data: